env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://laravel_backend:80/products
    - http://laravel_backend:80/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 0
    url: http://laravel_backend:80/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: rapport_scan7.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: rapport_scan7.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
