name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Installer les dépendances Laravel
        working-directory: backend
        run: composer install

      - name: Copier le fichier .env
        working-directory: backend
        run: cp .env.example .env

      - name: Générer la clé Laravel
        working-directory: backend
        run: php artisan key:generate

      - name: Lancer les tests Laravel
        working-directory: backend
        run: php artisan test

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Builder les images Docker
        run: docker compose build
